## NumPy 

NumPy is a python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy stands for Numerical Python.

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures

## Installation 

NumPy is installed on my PC because I installed Anaconda but if you 
installed Python without Anaconda, then you need to install NumPy with pip package installer : `pip install numpy`

In [1]:
import numpy 

In [2]:
arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### NumPy as np
NumPy is usually imported under the np alias, so:

In [3]:
import numpy as np

In [4]:
arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### To check NumPy version:

In [5]:
print(np.__version__)

1.18.1


### Creating a NumPy ndarray object

NumPy is used to work with arrays. The array object in NumPy is called `ndarray`.

We can create a NumPy ndarray object by using the `array()` function.

In [6]:
arr = np.array([1, 2, 3, 4])

print(arr)

print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


***
To create an ndarray, we can pass a **list, tuple or any array-like object** into the array() method, and it will be converted into an ndarray:

In [7]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


## Dimensions in Arrays

#### 0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

`example: a 0-D array with value 10`

In [8]:
arr = np.array(10)

print(arr)

10


#### 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array. These are the most common and basic arrays.

`example: a 1-D array with values of 10,20,30`

In [9]:
arr = np.array([10, 20, 30])

print(arr)

[10 20 30]


#### 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.
These are often used to represent matrix or 2nd order tensors.

`example: a 2-D array containing two arrays with the values 1,2,3 and 4,5,6`

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


#### 3-D Arrays
 
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

`example: Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6`

In [11]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
    
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Check the number of Dimensions

we can check the number of dimensions using the **`ndim`** attribute.

`example:`

In [12]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher Dimensional Arrays

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the `ndmin` argument.

`example: Create an array with 5 dimensions and verify that it has 5 dimensions`

In [13]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## NumPy Array Indexing

#### Access Array Elements

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

`example:`

In [14]:
arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])
print(arr[2] + arr[3])

1
2
7


***

#### Access 2-D Arrays

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

`example: Access the 2nd element on 1st dim`

In [15]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


`example: Access the 5th element on 2nd dim`

In [16]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd dim: ', arr[1, 4])

5th element on 2nd dim:  10


***

#### Access 3-D Arrays

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

`example: Access the third element of the second array of the first array`

In [17]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


##### Example Explained

`arr[0, 1, 2]` prints the value `6`.

And this is why:

The first number represents the first dimension, which contains two arrays:

[[1, 2, 3], [4, 5, 6]]

and:

[[7, 8, 9], [10, 11, 12]]

Since we selected `0`, we are left with the first array:

[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:

[1, 2, 3]

and:

[4, 5, 6]

Since we selected `1`, we are left with the second array:

[4, 5, 6]

The third number represents the third dimension, which contains three values:

4
5
6

Since we selected `2`, we end up with the third value:
6



#### Negative Indexing

Use negative indexing to access an array from the end.

`example: Print the last element from the 2nd dim`

In [18]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10
