## NumPy 

NumPy is a python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy stands for Numerical Python.

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures

## Installation 

NumPy is installed on my PC because I installed Anaconda but if you 
installed Python without Anaconda, then you need to install NumPy with pip package installer : `pip install numpy`

In [1]:
import numpy 

In [2]:
arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


#### NumPy as np
NumPy is usually imported under the np alias, so:

In [3]:
import numpy as np

In [4]:
arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


#### To check NumPy version:

In [5]:
print(np.__version__)

1.18.1


#### Creating a NumPy ndarray object

NumPy is used to work with arrays. The array object in NumPy is called `ndarray`.

We can create a NumPy ndarray object by using the `array()` function.

In [6]:
arr = np.array([1, 2, 3, 4])

print(arr)

print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


***
To create an ndarray, we can pass a **list, tuple or any array-like object** into the array() method, and it will be converted into an ndarray:

In [7]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


## Dimensions in Arrays

#### 0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

`example: a 0-D array with value 10`

In [8]:
arr = np.array(10)

print(arr)

10


#### 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array. These are the most common and basic arrays.

`example: a 1-D array with values of 10,20,30`

In [9]:
arr = np.array([10, 20, 30])

print(arr)

[10 20 30]


#### 2-D Arrays

An array that has 1-D arrays as its elements is called a 2-D array.
These are often used to represent matrix or 2nd order tensors.

`example: a 2-D array containing two arrays with the values 1,2,3 and 4,5,6`

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


#### 3-D Arrays
 
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

`example: Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6`

In [11]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
    
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Check the number of Dimensions

we can check the number of dimensions using the **`ndim`** attribute.

`example:`

In [12]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher Dimensional Arrays

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the `ndmin` argument.

`example: Create an array with 5 dimensions and verify that it has 5 dimensions`

In [13]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## NumPy Array Indexing

#### Access Array Elements

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

`example:`

In [14]:
arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])
print(arr[2] + arr[3])

1
2
7


***

#### Access 2-D Arrays

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

`example: Access the 2nd element on 1st dim`

In [15]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


`example: Access the 5th element on 2nd dim`

In [16]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd dim: ', arr[1, 4])

5th element on 2nd dim:  10


***

#### Access 3-D Arrays

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

`example: Access the third element of the second array of the first array`

In [17]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


##### Example Explained

`arr[0, 1, 2]` prints the value `6`.

And this is why:

The first number represents the first dimension, which contains two arrays:

[[1, 2, 3], [4, 5, 6]]

and:

[[7, 8, 9], [10, 11, 12]]

Since we selected `0`, we are left with the first array:

[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:

[1, 2, 3]

and:

[4, 5, 6]

Since we selected `1`, we are left with the second array:

[4, 5, 6]

The third number represents the third dimension, which contains three values:

4
5
6

Since we selected `2`, we end up with the third value:
6

***

#### Negative Indexing

Use negative indexing to access an array from the end.

`example: Print the last element from the 2nd dim`

In [18]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


***
## NumPy Array Slicing

#### Slicing arrays

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: `[start:end]`

We can also define the step, like this: `[start:end:step]`

* If we don't pass start its considered 0

* If we don't pass end its considered length of array in that dimension

* If we don't pass step its considered 1

`example: Slice elements from index 1 to index 5 from the following array`

**Note**: The result includes the start index, but excludes the end index.

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


`example: Slice elements from index 4 to the end of the array`

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


`example: Slice elements from the beginning to index 4 (not included)`

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


#### Negative Slicing

Use the minus operator to refer to an index from the end

`example: Slice from the index 3 from the end to index 1 from the end`

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


#### STEP

Use the `step` value to determine the step of the slicing

`example: Return every other element from index 1 to index 5`

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


#### Slicing 2-D Arrays

`example: From the second element, slice elements from index 1 to index 4 (not included)`

In [24]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


`example: From both elements, return index 2`

In [25]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


`example: From both elements, slice index 1 to index 4 (not included), this will return a 2-D array`

In [26]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


***
## NumPy Data Types

#### Data Types in Python

By default Python have these data types:

* `strings` - used to represent text data, the text is given under quote marks. eg. "ABCD"
* `integer` - used to represent integer numbers. eg. -1, -2, -3
* `float` - used to represent real numbers. eg. 1.2, 42.42
* `boolean` - used to represent True or False.
* `complex` - used to represent a number in complex plain. eg. 1.0 + 2.0j, 1.5 + 2.5

#### Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

* `i` - integer
* `b` - boolean
* `u` - unsigned integer
* `f` - float
* `c` - complex float
* `m` - timedelta
* `M` - datetime
* `O` - object
* `S` - string
* `U` - unicode string
* `V` - fixed chunk of memory for other type ( void )

#### Checking the Data Type of an Array

The NumPy array object has a property called `dtype` that returns the data type of the array

`example: Get the data type of an array object`

In [27]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


`example: Get the data type of an array containing strings`

In [28]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


#### Creating Arrays With a Defined Data Type

We use the `array()` function to create arrays, this function can take an optional argument: `dtype` that allows us to define the expected data type of the array elements.

`example: Create an array with data type string`

In [29]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


For `i`, `u`, `f`, `S` and `U` we can define size as well.

`example: Create an array with data type 4 bytes integer`

In [30]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


#### What if a Value Can Not Be Converted?

If a type is given in which elements can't be casted then NumPy will raise a ValueError.

`ValueError`: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.

`example: A non integer string like 'a' can not be converted to integer (will raise an error)`

In [31]:
# arr = np.array(['a', '2', '3'], dtype='i')

#### Converting Data Type on Existing Arrays

The best way to change the data type of an existing array, is to make a copy of the array with the `astype()` method.

The `astype()` function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like `'f'` for float, `'i'` for integer etc. or you can use the data type directly like `float` for float and `int` for integer.

`example: Change data type from float to integer by using 'i' as parameter value`

In [32]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


`example : Change data type from integer to boolean`

In [33]:
arr = np.array([1, 0, 5])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


***

## NumPy Array Copy vs View

#### The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

#### Copy

`example: Make a copy, change the original array, and display both arrays`

In [34]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


#### View

`example: Make a view, change the original array, and display both arrays`

In [35]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


`example: Make a view, change the view, and display both arrays`

In [36]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


#### Check if Array Owns it's Data

As mentioned above, copies own the data, and views do not own the data, but how can we check this?

Every NumPy array has the attribute `base` that returns `None` if the array owns the data.

Otherwise, the `base`  attribute refers to the original object.

`example: Print the value of the base attribute to check if an array owns it's data or not`

**Note**: The copy returns None. The view returns the original array.

In [37]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


***

## NumPy Array Shape

#### Shape of an Array

The shape of an array is the number of elements in each dimension.

#### Get the Shape of an Array

NumPy arrays have an attribute called `shape` that returns a tuple with each index having the number of corresponding elements.

`example: Print the shape of a 2-D array`

In [38]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


The example above returns **(2, 4)**, which means that the array has 2 dimensions, and each dimension has 4 elements.

`example: Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4`

In [39]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


Integers at every index tells about the number of elements the corresponding dimension has.

In the example above at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.

***

## NumPy Array Reshaping

#### Reshaping arrays
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

#### Reshape From 1-D to 2-D

`example: Convert the following 1-D array with 12 elements into a 2-D array.The outermost dimension will have 4 arrays, each with 3 elements.`


In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### Reshape From 1-D to 3-D

`example: Convert the following 1-D array with 12 elements into a 3-D array.The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements.`

In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#### Can We Reshape Into any Shape?

Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

`example: Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension`**`(will raise an error)`**

In [42]:
# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# newarr = arr.reshape(3, 3)

# print(newarr)

#### Returns Copy or View?

`example: Check if the returned array is a copy or a view`

In [43]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


The example above returns the original array, so it is a **view**.

#### Unknown Dimension

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass **`-1`** as the value, and NumPy will calculate this number for you.

`example: Convert 1D array with 8 elements to 3D array with 2x2 elements`

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

**Note:** We can not pass **`-1`** to more than one dimension.

#### Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use `reshape(-1)` to do this.

`example: Convert the array into a 1D array.`

In [44]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


**Note:** There are a lot of functions for changing the shapes of arrays in numpy `flatten`, `ravel` and also for rearranging the elements `rot90`, `flip`, `fliplr`, `flipud` etc. These fall under Intermediate to Advanced section of numpy.

***

## NumPy Array Iterating

#### Iterating Arrays

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

`example: Iterate on the elements of the following 1-D array`

In [45]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


#### Iterating 2-D Arrays

In a 2-D array it will go through all the rows.

`example: Iterate on the elements of the following 2-D array`

In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


**Note:** If we iterate on a n-D array it will go through n-1th dimension one by one.

To return the actual values, the scalars, we have to iterate the arrays in each dimension.

`example: Iterate on each scalar element of the 2-D array`

In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


#### Iterating 3-D Arrays

In a 3-D array it will go through all the 2-D arrays.

`example: Iterate on the elements of the following 3-D array`

In [48]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


To return the actual values, the scalars, we have to iterate the arrays in each dimension.

`example: Iterate down to the scalars`

In [49]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


#### Iterating Arrays Using nditer()

The function `nditer()` is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

#### Iterating on Each Scalar Element

In basic `for` loops, iterating through each scalar of an array we need to use `n for loops` which can be difficult to write for arrays with very high dimensionality.

`example: Iterate through the following 3-D array`

In [50]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


#### Iterating Array With Different Data Types

We can use `op_dtypes` argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in `nditer()` we pass `flags=['buffered']`

`example: Iterate through the array as a string`

In [51]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


#### Iterating With Different Step Size

We can use filtering and followed by iteration.

`example: Iterate through every scalar element of the 2D array skipping 1 element`

In [52]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


#### Enumerated Iteration Using ndenumerate()

Enumeration means mentioning sequence number of something one by one.

Sometimes we require corresponding index of the element while iterating, the `ndenumerate()` method can be used for those usecases.

`example: Enumerate on following 1D arrays elements`

In [53]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


`example: Enumerate on following 2D array's elements`

In [54]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


***

## NumPy Joining Array

#### Joining NumPy Arrays

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by `axes`.

We pass a sequence of arrays that we want to join to the **`concatenate()`** function, along with the axis. If axis is not explicitly passed, it is taken as `0`.

`example: Join two arrays`

In [55]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


`example: Join two 2-D arrays along rows (axis=1)`

In [56]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


#### Joining Arrays Using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

`example:`

In [57]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


#### Stacking Along Rows

NumPy provides a helper function: `hstack()` to stack along rows.

`example:`

In [58]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


#### Stacking Along Columns

NumPy provides a helper function: `vstack()`  to stack along columns.

`example:`

In [59]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


#### Stacking Along Height (depth)

NumPy provides a helper function: `dstack()`to stack along height, which is the same as depth.

`example:`

In [60]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


***

## NumPy Splitting Array

#### Splitting NumPy Arrays

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use **`array_split()`** for splitting arrays, we pass it the array we want to split and the number of splits.

`example: Split the array in 3 parts`

**Note:** The returned value is an array containing three arrays.

In [61]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


If the array has less elements than required, it will adjust from the end accordingly.

`example: Split the array in 4 parts`

In [62]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


#### Split Into Arrays

The return value of the `array_split()` method is an array containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element:

`example: Access the splitted arrays`

In [63]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


#### Splitting 2-D Arrays

Use the same syntax when splitting 2-D arrays.

Use the `array_split()` method, pass in the array you want to split and the number of splits you want to do.

`example: Split the 2-D array into three 2-D arrays`

In [64]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


The example above returns three 2-D arrays.

In addition, you can specify which axis you want to do the split around.

The example below also returns three 2-D arrays, but they are split along the row (axis=1).

`example: Split the 2-D array into three 2-D arrays along rows`

In [65]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


An alternate solution is using `hsplit()` opposite of `hstack()`

`example: Use the hsplit() method to split the 2-D array into three 2-D arrays along rows`

In [66]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


* **Note:** Similar alternates to `vstack()` and `dstack()` are available as `vsplit()` and `dsplit()`.

***

## NumPy Searching Arrays

#### Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the `where()` method.

`example: Find the indexes where the value is 4`

In [67]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


The example above will return a tuple: `(array([3, 5, 6],)`

Which means that the value `4` is present at `index 3, 5, and 6.`

`example: Find the indexes where the values are even`

In [68]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


`example: Find the indexes where the values are odd`

In [69]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


#### Search Sorted

There is a method called `searchsorted()` which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

* The `searchsorted()` method is assumed to be used on sorted arrays.

`example: Find the indexes where the value 7 should be inserted`

In [70]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


`The Example above explained:` The number 7 should be inserted on index 1 to remain the sort order. The method starts the search from the left and returns the first index where the number 7 is no longer larger than the next value.

By default the left most index is returned, but we can give `side='right'` to return the right most index instead.

`example: Find the indexes where the value 7 should be inserted, starting from the right`

In [71]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


`The Example above explained:` The number 7 should be inserted on index 2 to remain the sort order. The method starts the search from the right and returns the first index where the number 7 is no longer less than the next value.

To search for more than one value, use an array with the specified values.

`example: Find the indexes where the values 2, 4, and 6 should be inserted`


In [72]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


The returned value is an array: `[1 2 3]` containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.

***

## NumPy Sorting Arrays

#### Sorting Arrays

Sorting means putting elements in a ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called `sort()`, that will sort a specified array.

**Note:** This method returns a copy of the array, leaving the original array unchanged.

`example: Sort the array`

In [73]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


`example: Sort the array alphabetically`

In [74]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


`example: Sort a boolean array`

In [75]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


#### Sorting a 2-D Array

If you use the `sort()` method on a 2-D array, both arrays will be sorted:

`example: Sort a 2-D array`

In [76]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


***

## NumPy Filter Array

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

`A boolean index list is a list of booleans corresponding to indexes in the array.`

If the value at an index is `True` that element is contained in the filtered array, if the value at that index is `False` that element is excluded from the filtered array.

`example: Create an array from the elements on index 0 and 2`

In [77]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


The example above will return `[41, 43]`, why?

Because the new filter contains only the values where the filter array had the value True, in this case, index 0 and 2.

#### Creating the Filter Array

In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.

`example: Create a filter array that will return only values higher than 42`

In [78]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


`example: Create a filter array that will return only even elements from the original array`

In [79]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


#### Creating Filter Directly From Array

The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

`example: Create a filter array that will return only values higher than 42`

In [80]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


`example: Create a filter array that will return only even elements from the original array`

In [81]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


***

## Random Numbers in NumPy

#### What is a Random Number?

Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

#### Pseudo Random and True Random.

Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

We do not need truly random numbers, unless its related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).

In this tutorial we will be using pseudo random numbers.

#### Generate Random Number

NumPy offers the `random` module to work with random numbers.

`example: Generate a random integer from 0 to 100`

In [82]:
from numpy import random

In [83]:
x = random.randint(100)

print(x)

90


#### Generate Random Float

The random module's `rand()` method returns a random float between 0 and 1.

`example: Generate a random float from 0 to 1`

In [84]:
x = random.rand()

print(x)

0.8237426257551865


#### Generate Random Array

In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.

##### Integers

The `randint()` method takes a `size` parameter where you can specify the shape of an array.

`example: Generate a 1-D array containing 5 random integers from 0 to 100`

In [85]:
x=random.randint(100, size=(5))

print(x)

[29  4 89 56 58]


`example: Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100`

In [86]:
x = random.randint(100, size=(3, 5))

print(x)

[[38 88 97 35  5]
 [ 1 95 11 11 22]
 [76  4 12 10 17]]


##### Floats

The `rand()` method also allows you to specify the shape of the array.

`example: Generate a 1-D array containing 5 random floats`

In [87]:
x = random.rand(5)

print(x)

[0.35324129 0.57388011 0.46292574 0.03903677 0.87376326]


`example: Generate a 2-D array with 3 rows, each row containing 5 random numbers`

In [88]:
x = random.rand(3, 5)

print(x)

[[0.37017255 0.11214241 0.10551334 0.82734762 0.82567039]
 [0.02366674 0.43532502 0.77628745 0.76783675 0.5167476 ]
 [0.31999185 0.93441565 0.6573059  0.02202394 0.2158462 ]]


#### Generate Random Number From Array

The `choice()` method allows you to generate a random value based on an array of values.

The `choice()` method takes an array as a parameter and randomly returns one of the values.

`example: Return one of the values in an array`

In [89]:
x = random.choice([3, 5, 7, 9])

print(x)

3


The `choice()` method also allows you to return an array of values.

Add a `size` parameter to specify the shape of the array.

`example: Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9)`

In [90]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 7 7 3 3]
 [3 7 3 9 9]
 [5 5 3 9 7]]


***

## Random Data Distribution

#### What is Data Distribution?

Data Distribution is a list of all possible values, and how often each value occurs.

Such lists are important when working with statistics and data science.

The random module offer methods that returns randomly generated data distributions.

#### Random Distribution

A random distribution is a set of random numbers that follow a certain probability density function.

`Probability Density Function:` A function that describes a continuous probability. i.e. probability of all values in an array.

We can generate random numbers based on defined probabilities using the `choice()` method of the random module.

The `choice()` method allows us to specify the probability for each value.

The probability is set by a number between `0` and `1`, where 0 means that the value will never occur and 1 means that the value will always occur.

`Note: The sum of all probability numbers should be 1.`

`example:` Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.

The probability for the value to be 3 is set to be 0.1

The probability for the value to be 5 is set to be 0.3

The probability for the value to be 7 is set to be 0.6

The probability for the value to be 9 is set to be 0

In [91]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[5 7 7 7 7 5 3 5 5 5 5 7 7 5 7 5 3 5 7 7 7 7 5 7 5 5 7 7 7 5 7 7 7 7 7 7 7
 5 7 3 7 7 7 7 5 5 7 7 7 7 5 5 5 7 7 3 5 7 5 7 7 5 5 3 7 5 7 5 3 7 5 5 5 5
 7 7 7 3 3 3 7 5 7 5 3 7 7 7 5 3 7 7 7 5 5 5 5 3 7 7]


Even if you run the example above 100 times, the value 9 will never occur.

You can return arrays of any shape and size by specifying the shape in the `size` parameter.

`example: Same example as above, but return a 2-D array with 3 rows, each containing 5 values`

In [92]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[5 7 7 3 7]
 [7 7 7 7 7]
 [5 3 7 7 3]]


***

## NumPy ufuncs

#### What are ufuncs?

ufuncs stands for "Universal Functions" and they are NumPy functions that operates on the ndarray object.

#### Why use ufuncs?

ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

ufuncs also take additional arguments, like:

* `where` boolean array or condition defining where the operations should take place.

* `dtype` defining the return type of elements.

* `out` output array where the return value should be copied.

***

#### What is Vectorization?

`Converting iterative statements into a vector based operation is called vectorization.`

It is faster as modern CPUs are optimized for such operations.

`example:  Add the Elements of Two Lists` 

`list 1: [1, 2, 3, 4]`

`list 2: [4, 5, 6, 7]`

One way of doing it is to iterate over both of the lists and then sum each elements.

Without ufunc, we can use Python's built-in `zip()` method

In [93]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


NumPy has a ufunc for this, called `add(x, y)` that will produce the same result.

In [94]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]
